language: python

python:
  - "3.4"

env:
  - DJANGO_VERSION=1.7.7 MIGRATE='./manage.py migrate'

script:
  - python3 manage.py migrate

install:
  - apt-get -y install python3-pip python-dev
  - pip3 install Django == 1.7.7
  - apt-get install postgresql postgresql-contrib
  - apt-get install python3-psycopg2
  - pip3 install django-bootstrap3==6.2.2
  - pip3 install django-foundation
  - pip3 install django-zurb-foundation

script:
  - python3 manage.py test

after_sucess:
  - coverals