language: python

python:
  - "3.4"

branches:
  only:
    - travis

services:
  - postgresql

env:
  - DJANGO_VERSION=1.7.7 MIGRATE='./manage.py migrate'

script:
  - python3 manage.py migrate

befote_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U vrtualenvwrapper
  - python3 -V
  - pip3 -V
  - sudo apt-get build-dep python-psycopg2
  - sudo -i -u postgres
  - createuser -drlP kanjam
  - psql
  - psql -c 'create database kanjam;' -U kanjam

install:
  - pip3 install Django==$DJANGO_VERSION
  - sudo apt-get install python3-psycopg2
  - pip3 install django-bootstrap3==6.2.2
  - pip3 install django-foundation
  - pip3 install django-zurb-foundation
  - pip3 install psycopg2 

script: python3 manage.py test

after_sucess:
  - coveralls