language: python

python:
  - "3.4"

env:
  - DJANGO_VERSION=1.7.7 MIGRATE='./manage.py migrate'

script:
  - python3 manage.py migrate

befote_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U vrtualenvwrapper
  - python3 -V
  - pip3 -V  

install:
  - pip3 install Django==$DJANGO_VERSION
  - sudo apt-get install python3-psycopg2
  - sudo pip3 install django-bootstrap3==6.2.2
  - sudo pip3 install django-foundation
  - sudo pip3 install django-zurb-foundation

script:
  - python3 manage.py test

after_sucess:
  - coverals