language: python
sudo: required

python:
  - "3.4.3"

services:
  - postgresql

env:
  - DJANGO_VERSION=1.7.7 MIGRATE='./manage.py migrate'

install:
  - pip3 install Django==$DJANGO_VERSION
  - sudo apt-get install python3-psycopg2
  - pip3 install django-bootstrap3==6.2.2
  - pip3 install django-foundation
  - pip3 install django-zurb-foundation
  - sudo apt-get build-dep python-psycopg2
  - pip3 install psycopg2 
  - pip3 install --upgrade setuptools

before_script:
  - sudo -u -i postgres
  - sudo - u postgres createuser kanjam
  - psql -c 'create database kanjam with owner kanjam;'

script:
  - ./manage.py test