language: python

env:
  - DJANGO_VERSION=1.7.7 MIGRATE='./manage.py migrate'

python:
  - "3.4"

install:
  - pip3 install Django==$DJANGO_VERSION
  - sudo apt-get install python3 python-pip
  - sudo apt-get install python-psycopg2
  - sudo pip install django-bootstrap3
  - sudo pip install django-zurb-foundation

script:
  - ./manage.py test