language: python
sudo: required

python:
  - "3.4.3"

services:
  - postgresql

addons:
  - postgresql: "9.3"

env:
  - DJANGO_VERSION=1.7.7 MIGRATE='./manage.py migrate'

install:
  - pip3 install Django==$DJANGO_VERSION
  - sudo apt-get install python3-psycopg2
  - pip3 install django-bootstrap3==6.2.2
  - pip3 install django-foundation
  - pip3 install django-zurb-foundation
  - sudo apt-get build-dep python-psycopg2
  - pip3 install psycopg2 
  - pip3 install --upgrade setuptools

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo cp /etc/postgresql/9.2/main/pg_hba.conf ./
  - sudo apt-get remove postgresql postgresql-9.2 -qq --purge
  - source /etc/lsb-release
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ $DISTRIB_CODENAME-pgdg main" > pgdg.list
  - sudo mv pgdg.list /etc/apt/sources.list.d/
  - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install postgresql-9.3 postgresql-contrib-9.3 -qq
  - sudo /etc/init.d/postgresql stop
  - sudo cp ./pg_hba.conf /etc/postgresql/9.3/main
  - sudo /etc/init.d/postgresql start
  - npm install -g bower
  - sed -i -e 's/getpass.getuser()/"postgres"/g' kanjam/settings.py
  - psql -c 'create database kanjam;' -U postgres

script:
  - ./manage.py migrate
  - ./manage.py bower install
  - ./test_and_check_qa.sh