language: python

python:
  - "3.4"

branches:
  only:
    - travis

services:
  - postgresql

env:
  - DJANGO_VERSION=1.7.7 MIGRATE='./manage.py migrate'

before_srcript:
  - sudo -u -i postgres
  - psql -c 'createuser -drlP kanjam;'
  - psql -c 'create database kanjam with owner kanjam;'

script:
  - ./manage.py migrate

befote_install:
  - apt-get install python3-pip
  - pip3 install -U setuptools
  - pip3 install -U vrtualenvwrapper
  - python3 -V
  - pip3 -V
  
install:
  - pip3 install Django==$DJANGO_VERSION
  - sudo apt-get install python3-psycopg2
  - pip3 install django-bootstrap3==6.2.2
  - pip3 install django-foundation
  - pip3 install django-zurb-foundation
  - sudo apt-get build-dep python-psycopg2
  - pip3 install psycopg2 

script: 
  - python3 manage.py test